server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coffeeshop?currentSchema=public
    username: octavia
    password: mysecretpassword

  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true

management:
  metrics:
    enable:
      all: true
    tags:
      application: coffeeshop
  endpoints:
    web:
      exposure:
        include: '*'
